name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v2
      - run: npm ci
      - run: npm test
